// ═══════════════════════════════════════════════════════════════
// Canopy Maintenance Engine — Task Templates & Seasonal Logic
// ═══════════════════════════════════════════════════════════════
import type { TaskFrequency, TaskPriority, EquipmentCategory, TaskSchedulingType } from '@/types';

export type ClimateRegion = 'south' | 'north' | 'mountain' | 'coastal' | 'desert' | 'midwest' | 'all';

export interface TaskTemplate {
  id: string;
  title: string;
  description: string;
  instructions: string[];
  category: EquipmentCategory | 'general' | 'lawn' | 'pool' | 'deck' | 'seasonal' | 'pest_control' | 'fireplace';
  priority: TaskPriority;
  frequency: TaskFrequency;
  scheduling_type: TaskSchedulingType; // 'dynamic' = next due relative to completion, 'seasonal' = fixed calendar months
  interval_days?: number; // for dynamic tasks: days between occurrences
  applicable_months: number[]; // for seasonal tasks: which months; for dynamic: used only on first generation
  estimated_minutes: number;
  estimated_cost: number;
  requires_equipment?: EquipmentCategory;
  requires_home_feature?: string; // e.g., 'has_pool', 'has_deck'
  requires_countertop_type?: string[]; // specific countertop types that trigger this task
  service_purpose?: string;
  items_to_have_on_hand?: string[];
  applicable_regions?: ClimateRegion[]; // undefined = all regions
}

/**
 * Maps US states to climate regions for task filtering.
 * Tasks with applicable_regions will only show for homeowners in matching states.
 */
export const STATE_TO_REGION: Record<string, ClimateRegion> = {
  // South / Hot-Humid
  TX: 'south', FL: 'south', GA: 'south', AL: 'south', MS: 'south',
  LA: 'south', SC: 'south', NC: 'south', TN: 'south', AR: 'south',
  // North / Cold
  MN: 'north', WI: 'north', MI: 'north', ME: 'north', VT: 'north',
  NH: 'north', NY: 'north', MA: 'north', CT: 'north', RI: 'north',
  PA: 'north', NJ: 'north', ND: 'north', SD: 'north',
  // Mountain / High-altitude
  CO: 'mountain', MT: 'mountain', WY: 'mountain', ID: 'mountain',
  UT: 'mountain', NM: 'mountain',
  // Coastal
  CA: 'coastal', OR: 'coastal', WA: 'coastal', HI: 'coastal',
  // Desert / Arid
  AZ: 'desert', NV: 'desert',
  // Midwest
  OH: 'midwest', IN: 'midwest', IL: 'midwest', IA: 'midwest',
  MO: 'midwest', KS: 'midwest', NE: 'midwest', OK: 'midwest',
  // Default these to regions that fit best
  VA: 'south', WV: 'north', KY: 'midwest', MD: 'north',
  DE: 'north', DC: 'north', AK: 'north',
};

/** Returns the climate region for a state code, or 'midwest' as a reasonable default */
export const getClimateRegion = (state?: string): ClimateRegion => {
  if (!state) return 'midwest';
  return STATE_TO_REGION[state.toUpperCase()] || 'midwest';
};

// ─── Monthly & Seasonal Task Templates ───
export const TASK_TEMPLATES: TaskTemplate[] = [
  // ═══ HVAC ═══
  {
    id: 'hvac-filter-change',
    title: 'Replace HVAC Air Filters',
    description: 'Dirty filters restrict airflow, increase energy bills, and reduce air quality. Replace every 90 days for standard pleated filters, or every 30 days for fiberglass.',
    instructions: [
      'Turn off your HVAC system',
      'Locate the filter(s) — usually near the return air vent or inside the air handler',
      'Note the filter size printed on the frame (e.g., 20x25x1)',
      'Slide out the old filter and check the airflow direction arrow',
      'Insert the new filter with the arrow pointing toward the blower',
      'Turn the system back on',
    ],
    category: 'hvac',
    priority: 'high',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 10,
    estimated_cost: 15,
    requires_equipment: 'hvac',
  },
  {
    id: 'hvac-spring-tuneup',
    title: 'Schedule Spring AC Tune-Up',
    description: 'Annual professional AC maintenance before summer. Catches issues early and improves efficiency by up to 15%.',
    instructions: [
      'Call your HVAC service provider to schedule a tune-up',
      'Ensure they check refrigerant levels, clean coils, and test the thermostat',
      'Clear at least 2 feet around the outdoor condenser unit',
      'Replace your air filter before they arrive',
    ],
    category: 'hvac',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3, 4],
    estimated_minutes: 90,
    estimated_cost: 150,
    requires_equipment: 'hvac',
  },
  {
    id: 'hvac-fall-furnace',
    title: 'Schedule Fall Furnace Tune-Up',
    description: 'Annual furnace inspection before heating season. Ensures safe operation and catches carbon monoxide risks.',
    instructions: [
      'Schedule a professional furnace inspection',
      'Replace the air filter',
      'Test your thermostat — switch to heat mode and verify it kicks on',
      'Check for unusual noises or smells when the furnace first starts',
      'Ensure CO detectors near the furnace are working',
    ],
    category: 'hvac',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [9, 10],
    estimated_minutes: 60,
    estimated_cost: 120,
    requires_equipment: 'hvac',
  },

  // ═══ WATER HEATER ═══
  {
    id: 'water-heater-flush',
    title: 'Flush Water Heater',
    description: 'Sediment buildup reduces efficiency and shortens tank life. Annual flushing removes buildup and keeps your water heater running efficiently.',
    instructions: [
      'Turn off the water heater (gas: pilot setting; electric: breaker off)',
      'Connect a garden hose to the drain valve at the bottom',
      'Run the hose to a drain or outside',
      'Open the drain valve and let water flow until it runs clear (5-10 minutes)',
      'Close the drain valve and turn the water supply back on',
      'Once the tank is full, turn the heater back on',
    ],
    category: 'water_heater',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [4, 10],
    estimated_minutes: 30,
    estimated_cost: 0,
    requires_equipment: 'water_heater',
  },
  {
    id: 'water-heater-anode-rod',
    title: 'Check Anode Rod',
    description: 'Check every 3-5 years. The sacrificial anode rod prevents tank corrosion.',
    instructions: [
      'Locate the anode rod — typically on top of the water heater',
      'Use a 1-1/16" socket wrench to unscrew it',
      'Pull it out and inspect — if less than 1/2" thick or coated in calcium, replace it',
      'New rods cost $20-50 and take 10 minutes to swap',
    ],
    category: 'water_heater',
    priority: 'medium',
    frequency: 'as_needed',
    scheduling_type: 'seasonal',
    applicable_months: [4],
    estimated_minutes: 20,
    estimated_cost: 30,
    requires_equipment: 'water_heater',
  },

  // ═══ ROOF & GUTTERS ═══
  {
    id: 'gutter-clean-spring',
    title: 'Clean Gutters (Spring)',
    description: 'Remove debris from winter and spring pollen. Clogged gutters cause water damage to fascia, foundation, and landscaping.',
    instructions: [
      'Use a sturdy ladder with a stabilizer bar',
      'Wear gloves and scoop debris from each gutter section',
      'Flush gutters with a hose to check drainage',
      'Check downspouts for clogs — tap them and listen for hollow sound',
      'Ensure downspout extensions direct water 4-6 feet from the foundation',
      'Inspect gutter hangers and resecure any loose sections',
    ],
    category: 'roof',
    priority: 'high',
    frequency: 'biannual',
    scheduling_type: 'seasonal',
    applicable_months: [4, 5],
    estimated_minutes: 60,
    estimated_cost: 0,
    requires_home_feature: 'has_gutters',
  },
  {
    id: 'gutter-clean-fall',
    title: 'Clean Gutters (Fall)',
    description: 'Clear leaves before winter. Ice dams form when clogged gutters prevent drainage.',
    instructions: [
      'Wait until most leaves have fallen before cleaning',
      'Remove all debris from gutters and downspouts',
      'Flush with water to verify proper drainage',
      'Check for any damage or sagging sections',
      'Consider gutter guards if leaf buildup is severe',
    ],
    category: 'roof',
    priority: 'high',
    frequency: 'biannual',
    scheduling_type: 'seasonal',
    applicable_months: [11],
    estimated_minutes: 60,
    estimated_cost: 0,
    requires_home_feature: 'has_gutters',
  },
  {
    id: 'roof-inspection',
    title: 'Visual Roof Inspection',
    description: 'Look for damaged, missing, or curling shingles. Catching issues early prevents leaks and expensive repairs.',
    instructions: [
      'Use binoculars from the ground — no need to climb on the roof',
      'Look for missing, cracked, or curling shingles',
      'Check flashing around chimneys, vents, and skylights',
      'Look for dark streaks (algae) or moss growth',
      'Check inside your attic for daylight, water stains, or sagging',
      'If you spot issues, call a roofer for a professional inspection',
    ],
    category: 'roof',
    priority: 'medium',
    frequency: 'biannual',
    scheduling_type: 'seasonal',
    applicable_months: [4, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },

  // ═══ SAFETY ═══
  {
    id: 'smoke-co-test',
    title: 'Test Smoke & CO Detectors',
    description: 'Test every 6 months. Replace batteries annually.',
    instructions: [
      'Press and hold the test button on each detector',
      'It should beep loudly within a few seconds',
      'If the beep is weak or absent, replace the battery',
      'Replace the entire unit if it is more than 10 years old',
      'Ensure detectors are on every level and near bedrooms',
    ],
    category: 'safety',
    priority: 'high',
    frequency: 'biannual',
    scheduling_type: 'dynamic',
    interval_days: 180,
    applicable_months: [4, 10],
    estimated_minutes: 10,
    estimated_cost: 0,
  },
  {
    id: 'fire-extinguisher-check',
    title: 'Check Fire Extinguishers',
    description: 'Verify the pressure gauge is in the green zone and the unit is accessible. Replace if expired.',
    instructions: [
      'Check the pressure gauge — needle should be in the green zone',
      'Verify the pin and tamper seal are intact',
      'Look for visible damage, rust, or dents',
      'Ensure it is easily accessible (kitchen, garage, workshop)',
      'Replace if more than 12 years old or if the gauge shows low pressure',
    ],
    category: 'safety',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [1],
    estimated_minutes: 5,
    estimated_cost: 0,
    requires_home_feature: 'has_fire_extinguisher',
  },

  // ═══ PLUMBING ═══
  {
    id: 'winterize-hose-bibs',
    title: 'Winterize Hose Bibs',
    description: 'Disconnect hoses and shut off exterior water supply before the first freeze to prevent burst pipes.',
    instructions: [
      'Disconnect all garden hoses from outdoor faucets',
      'Drain any remaining water from the hoses and store them',
      'If you have interior shutoff valves for outdoor faucets, close them',
      'Open the outdoor faucet to drain any trapped water',
      'Install insulated hose bib covers on each outdoor faucet',
      'If you have a sprinkler system, have it professionally blown out',
    ],
    category: 'plumbing',
    priority: 'urgent',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [10, 11],
    estimated_minutes: 20,
    estimated_cost: 10,
  },
  {
    id: 'check-for-leaks',
    title: 'Check for Water Leaks',
    description: 'Inspect under sinks, around toilets, and near the water heater for drips or moisture. Small leaks become big problems fast.',
    instructions: [
      'Check under every sink for drips or moisture',
      'Look around the base of each toilet',
      'Inspect the water heater area for puddles',
      'Check the washing machine hoses for bulging or cracks',
      'Look at ceilings for water stains (sign of a leak above)',
      'Check your water meter — if it moves when all faucets are off, you have a leak',
    ],
    category: 'plumbing',
    priority: 'medium',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },

  // ═══ EXTERIOR ═══
  {
    id: 'dryer-vent-clean',
    title: 'Clean Dryer Vent',
    description: 'Lint buildup in dryer vents is a leading cause of house fires. Clean annually or more often if you notice longer drying times.',
    instructions: [
      'Pull the dryer away from the wall and disconnect the vent hose',
      'Use a dryer vent brush kit to clean inside the vent duct',
      'Clean the vent from the outside too — remove the exterior cover and brush out',
      'Check the vent flap moves freely and is not blocked by debris',
      'Reconnect everything and push the dryer back',
      'Run a test cycle to verify proper airflow',
    ],
    category: 'appliance',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3],
    estimated_minutes: 30,
    estimated_cost: 0,
  },
  {
    id: 'garage-door-maintenance',
    title: 'Garage Door Maintenance',
    description: 'Lubricate moving parts and test safety features. A well-maintained garage door lasts 15-30 years.',
    instructions: [
      'Spray silicone lubricant on hinges, rollers, and tracks',
      'Test the auto-reverse by placing a 2x4 under the door',
      'Test the photoelectric sensors by breaking the beam during closing',
      'Tighten any loose bolts on the track brackets',
      'Check the weatherstripping at the bottom for cracks',
      'Listen for grinding or scraping — may indicate worn rollers',
    ],
    category: 'garage',
    priority: 'medium',
    frequency: 'biannual',
    scheduling_type: 'seasonal',
    applicable_months: [4, 10],
    estimated_minutes: 20,
    estimated_cost: 5,
  },

  // ═══ LAWN & LANDSCAPE ═══
  {
    id: 'spring-lawn-care',
    title: 'Spring Lawn Care',
    description: 'Rake, dethatch if needed, apply pre-emergent herbicide, and start mowing when grass reaches 3-4 inches.',
    instructions: [
      'Rake to remove dead grass and leaves',
      'Apply pre-emergent herbicide before soil temp reaches 55°F',
      'Overseed any bare or thin spots',
      'Begin mowing when grass is actively growing (3-4 inches)',
      'Set mower height to the tallest recommended setting for your grass type',
      'Apply a slow-release fertilizer if your lawn has not been fed since fall',
    ],
    category: 'lawn',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3, 4],
    estimated_minutes: 120,
    estimated_cost: 40,
  },
  {
    id: 'fall-lawn-care',
    title: 'Fall Lawn Care',
    description: 'Aerate, overseed, and apply fall fertilizer. This is the most impactful time to feed your lawn.',
    instructions: [
      'Aerate your lawn (rent an aerator or hire a pro)',
      'Overseed with appropriate grass seed for your lawn type',
      'Apply fall fertilizer — this is the most important feeding of the year',
      'Continue mowing until grass stops growing',
      'Lower mower height on the final cut of the season',
      'Remove fallen leaves — they smother grass if left over winter',
    ],
    category: 'lawn',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [9, 10],
    estimated_minutes: 180,
    estimated_cost: 60,
  },
  {
    id: 'tree-inspection',
    title: 'Inspect Trees & Prune',
    description: 'Look for dead branches, disease, and structural issues. Prune deciduous trees in late winter while dormant.',
    instructions: [
      'Walk around each tree and look up for dead or hanging branches',
      'Check trunks for cracks, cavities, or fungal growth',
      'Look for branches touching or near the house or power lines',
      'Prune dead/diseased branches at the collar (do not leave stubs)',
      'For large trees (>15 ft), hire a certified arborist',
      'Mulch around tree bases — 2-4 inches, kept 6 inches from the trunk',
    ],
    category: 'lawn',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [2, 3],
    estimated_minutes: 60,
    estimated_cost: 0,
  },

  // ═══ POOL ═══
  {
    id: 'pool-opening',
    title: 'Open Pool for Season',
    description: 'Remove cover, clean, balance chemicals, and start the filter system.',
    instructions: [
      'Remove and clean the pool cover',
      'Remove any winterizing plugs from return lines',
      'Reconnect the pump and filter system',
      'Fill the pool to the proper water level',
      'Run the pump and check for leaks',
      'Test and balance water chemistry (pH: 7.2-7.6, chlorine: 1-3 ppm)',
      'Vacuum and brush the pool walls and floor',
    ],
    category: 'pool',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [4, 5],
    estimated_minutes: 180,
    estimated_cost: 100,
    requires_home_feature: 'has_pool',
  },
  {
    id: 'pool-weekly',
    title: 'Monthly Pool Maintenance Check',
    description: 'Monthly check of pool chemicals, filter, and equipment. Establish a weekly routine for skimming, vacuuming, and chemical testing.',
    instructions: [
      'Skim the surface for leaves and debris',
      'Empty skimmer and pump baskets',
      'Test water chemistry (pH, chlorine, alkalinity)',
      'Add chemicals as needed to maintain proper balance',
      'Vacuum the pool floor',
      'Brush walls and tile line',
      'Check filter pressure — clean or backwash if 8-10 PSI above normal',
    ],
    category: 'pool',
    priority: 'high',
    frequency: 'monthly',
    scheduling_type: 'dynamic',
    interval_days: 30,
    applicable_months: [5, 6, 7, 8, 9],
    estimated_minutes: 30,
    estimated_cost: 20,
    requires_home_feature: 'has_pool',
  },

  // ═══ DECK ═══
  {
    id: 'deck-spring-clean',
    title: 'Spring Deck Cleaning & Inspection',
    description: 'Power wash, inspect for damage, and apply sealer/stain if needed. A maintained deck lasts 25+ years.',
    instructions: [
      'Sweep the deck thoroughly',
      'Power wash with a fan tip (not a zero-degree tip — it can damage wood)',
      'Inspect for loose boards, popped nails, or splintering',
      'Check the ledger board connection to the house',
      'Look underneath for rot, insect damage, or structural issues',
      'If the deck fails the water bead test, plan to reseal/stain',
    ],
    category: 'deck',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [4, 5],
    estimated_minutes: 120,
    estimated_cost: 0,
    requires_home_feature: 'has_deck',
  },
  {
    id: 'deck-seal-stain',
    title: 'Seal or Stain Deck',
    description: 'Apply deck sealer or stain every 2-3 years to protect against moisture, UV, and wear.',
    instructions: [
      'Clean the deck thoroughly first (power wash 1-2 days before)',
      'Ensure the deck is completely dry (48 hours of dry weather)',
      'Apply deck cleaner/brightener if needed',
      'Use a pump sprayer, roller, or brush to apply stain/sealer',
      'Work in manageable sections, maintaining a wet edge',
      'Apply a second coat if recommended by the product',
      'Allow 24-48 hours to dry before foot traffic',
    ],
    category: 'deck',
    priority: 'medium',
    frequency: 'as_needed',
    scheduling_type: 'seasonal',
    applicable_months: [5, 6, 9],
    estimated_minutes: 240,
    estimated_cost: 100,
    requires_home_feature: 'has_deck',
  },

  // ═══ FIREPLACE ═══
  {
    id: 'fireplace-chimney-inspection',
    title: 'Annual Chimney Inspection & Sweep',
    description: 'Have a certified chimney sweep inspect and clean your chimney annually before heating season. Creosote buildup is a leading cause of chimney fires.',
    instructions: [
      'Schedule a CSIA-certified chimney sweep',
      'They will inspect the flue liner, damper, and cap',
      'Creosote buildup greater than 1/8 inch should be removed',
      'Check for cracks in the flue liner or mortar joints',
      'Verify the chimney cap and spark arrestor are intact',
      'Test the damper opens and closes fully',
    ],
    category: 'fireplace',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [9, 10],
    estimated_minutes: 90,
    estimated_cost: 200,
    requires_home_feature: 'has_fireplace',
  },
  {
    id: 'fireplace-wood-burning-clean',
    title: 'Clean Firebox & Ash Removal (Wood Burning)',
    description: 'Remove ash buildup from wood-burning fireplaces. A thin layer of ash (1 inch) helps insulate and improve combustion, but excess ash restricts airflow.',
    instructions: [
      'Wait at least 24 hours after the last fire before cleaning',
      'Wear a dust mask and gloves',
      'Use a fireplace shovel to scoop ash into a metal bucket',
      'Leave about 1 inch of ash on the floor of the firebox',
      'Dispose of ashes in a metal container outdoors, away from structures',
      'Inspect the firebrick for cracks — replace any damaged bricks',
      'Check the fireplace screen or glass doors for damage',
    ],
    category: 'fireplace',
    priority: 'medium',
    frequency: 'monthly',
    scheduling_type: 'seasonal',
    applicable_months: [10, 11, 12, 1, 2, 3],
    estimated_minutes: 20,
    estimated_cost: 0,
    requires_home_feature: 'has_fireplace',
  },
  {
    id: 'fireplace-gas-inspection',
    title: 'Gas Fireplace Annual Service',
    description: 'Have a qualified technician inspect your gas fireplace annually. Check for gas leaks, clean the burner assembly, and verify the pilot light and thermocouple.',
    instructions: [
      'Schedule a gas fireplace service with a qualified technician',
      'They should check all gas connections for leaks',
      'Clean the burner ports and logs of dust and debris',
      'Inspect the thermocouple and thermopile',
      'Check the blower fan if equipped',
      'Clean the glass panel inside and out',
      'Test the remote control and wall switch',
    ],
    category: 'fireplace',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [9, 10],
    estimated_minutes: 60,
    estimated_cost: 150,
    requires_home_feature: 'has_fireplace',
  },
  {
    id: 'fireplace-check-damper',
    title: 'Check Fireplace Damper & Seal',
    description: 'Ensure your fireplace damper opens and closes properly. A stuck or leaky damper wastes energy and can let moisture, pests, and cold air into your home.',
    instructions: [
      'Open and close the damper — it should move freely',
      'With the damper closed, hold a lit match near the opening — if the flame flickers, the damper is leaking',
      'Check the damper handle or chain mechanism for rust or damage',
      'If the damper leaks, consider a top-sealing damper replacement',
      'For gas fireplaces: the damper must always be open or have a clamp — never fully close it',
    ],
    category: 'fireplace',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [9],
    estimated_minutes: 10,
    estimated_cost: 0,
    requires_home_feature: 'has_fireplace',
  },

  // ═══ SPRINKLER SYSTEM ═══
  {
    id: 'sprinkler-spring-startup',
    title: 'Spring Sprinkler System Startup',
    description: 'Activate your irrigation system for the season. Gradually pressurize the lines and check each zone for leaks, broken heads, and coverage gaps.',
    instructions: [
      'Slowly open the main water valve to the sprinkler system (avoid water hammer)',
      'Walk each zone while it runs and check for broken or tilted heads',
      'Look for pooling water that indicates a cracked line',
      'Adjust sprinkler heads so they are not spraying sidewalks, driveways, or the house',
      'Check the controller schedule and update run times for the season',
      'Replace any cracked or broken sprinkler heads',
      'Test rain sensor if you have one',
    ],
    category: 'outdoor',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3, 4],
    estimated_minutes: 45,
    estimated_cost: 10,
    requires_home_feature: 'has_sprinkler_system',
  },
  {
    id: 'sprinkler-winterize',
    title: 'Winterize Sprinkler System (Blowout)',
    description: 'Hire a professional to blow out your sprinkler lines with compressed air before the first freeze. Trapped water in lines will freeze and crack pipes.',
    instructions: [
      'Schedule a sprinkler blowout with a landscape company',
      'Turn off the main water supply to the sprinkler system',
      'The technician will use an air compressor to blow water from each zone',
      'Each zone should be blown until no water comes out of the heads',
      'Insulate the backflow preventer with a cover or towels',
      'Set the controller to rain/off mode for winter',
    ],
    category: 'outdoor',
    priority: 'urgent',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [10, 11],
    estimated_minutes: 30,
    estimated_cost: 75,
    requires_home_feature: 'has_sprinkler_system',
  },
  {
    id: 'sprinkler-head-check',
    title: 'Mid-Season Sprinkler Head Check',
    description: 'Walk your property and check each sprinkler zone for tilted heads, clogged nozzles, and dry spots. Mowing and foot traffic knock heads out of alignment.',
    instructions: [
      'Run each zone one at a time for 2-3 minutes',
      'Look for heads that are not popping up, are tilted, or spray erratically',
      'Check for dry patches in the lawn — may indicate a clogged nozzle',
      'Clear grass and dirt from around sunken heads',
      'Adjust rotor heads for proper arc and distance',
      'Replace any cracked or broken heads',
    ],
    category: 'outdoor',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [6, 7],
    estimated_minutes: 30,
    estimated_cost: 5,
    requires_home_feature: 'has_sprinkler_system',
  },

  // ═══ SEASONAL GENERAL ═══
  {
    id: 'spring-exterior-walkthrough',
    title: 'Spring Exterior Walkthrough',
    description: 'Walk the perimeter of your home checking for winter damage — cracks in foundation, caulk gaps, damaged siding.',
    instructions: [
      'Walk the entire perimeter of your home',
      'Check foundation for new cracks (mark them with tape to monitor)',
      'Inspect caulking around windows and doors — recaulk any gaps',
      'Look for damaged or loose siding, trim, or fascia',
      'Check grading — soil should slope away from the foundation',
      'Inspect the driveway and walkways for heaving or cracks',
      'Clear any debris from window wells',
    ],
    category: 'general',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3, 4],
    estimated_minutes: 30,
    estimated_cost: 0,
  },
  {
    id: 'fall-winterize',
    title: 'Fall Winterization Checklist',
    description: 'Prepare your entire home for winter — the most important seasonal maintenance event of the year.',
    instructions: [
      'Winterize hose bibs and sprinkler system',
      'Reverse ceiling fan direction (clockwise in winter)',
      'Check weatherstripping on all exterior doors',
      'Inspect and clean the chimney before first use',
      'Test the furnace — turn on heat mode and verify operation',
      'Check insulation in the attic — add more if you can see the joists',
      'Caulk any gaps around windows and exterior penetrations',
      'Check that your emergency kit is stocked (flashlights, batteries, water)',
    ],
    category: 'seasonal',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [10],
    estimated_minutes: 120,
    estimated_cost: 30,
  },

  // ═══ KITCHEN (from Proventive) ═══
  {
    id: 'refrigerator-coils-clean',
    title: 'Vacuum Refrigerator Coils & Compressor',
    description: 'Dust and pet hair buildup on refrigerator coils forces the compressor to work harder, reducing efficiency and lifespan. Clean every 6-12 months.',
    instructions: [
      'Unplug the refrigerator or turn off the breaker',
      'Locate the coils — usually behind or underneath the fridge',
      'Use a coil brush or vacuum with a brush attachment to remove dust and debris',
      'Clean the condenser fan blade if accessible',
      'Wipe down the area behind/under the fridge',
      'Plug the refrigerator back in',
      'Check the door seals while you are at it — a dollar bill should hold when closed in the seal',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'biannual',
    scheduling_type: 'dynamic',
    interval_days: 180,
    applicable_months: [3, 9],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'garbage-disposal-clean',
    title: 'Clean & Sharpen Garbage Disposal',
    description: 'Grease and food buildup causes odors and dulls the blades. Regular cleaning keeps it fresh and cuts efficiently.',
    instructions: [
      'Turn off the disposal and NEVER put your hand inside',
      'Drop a handful of ice cubes and a cup of rock salt into the disposal',
      'Run the disposal with cold water for 30 seconds — ice sharpens the blades',
      'Cut a lemon or lime in half and grind it to deodorize',
      'Pour 1/2 cup baking soda followed by 1 cup vinegar — let foam for 10 minutes',
      'Flush with hot water for 30 seconds',
      'Clean the rubber splash guard with a scrub brush and dish soap',
    ],
    category: 'appliance',
    priority: 'low',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 10,
    estimated_cost: 0,
  },
  {
    id: 'vent-hood-degrease',
    title: 'Degrease & Clean Range Vent Hood',
    description: 'Grease buildup on your range hood filter restricts airflow, causes odors, and is a fire hazard. Clean the filter and housing quarterly.',
    instructions: [
      'Remove the vent hood filter(s)',
      'Soak in hot water with dish soap and baking soda for 15-20 minutes',
      'Scrub with a non-abrasive brush to remove grease',
      'Wipe down the hood interior and exterior with a degreasing cleaner',
      'Rinse and dry the filter completely before reinstalling',
      'If you have a charcoal filter (recirculating hood), replace it every 3-6 months',
      'Check that the fan operates on all speeds',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'dishwasher-clean',
    title: 'Clean Dishwasher Interior & Filter',
    description: 'Food particles and mineral deposits build up in the filter and spray arms, reducing cleaning power and causing odors.',
    instructions: [
      'Remove the bottom rack and locate the filter (usually at the base)',
      'Twist and pull out the cylindrical filter',
      'Rinse under hot water and scrub with a soft brush to remove debris',
      'Check the spray arms for clogged holes — use a toothpick to clear them',
      'Wipe down the door edges, gasket, and interior walls',
      'Place a cup of white vinegar on the top rack and run a hot cycle empty',
      'Sprinkle 1 cup of baking soda on the bottom and run a short hot cycle',
      'Reinstall the clean filter',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },
  {
    id: 'stone-countertop-seal',
    title: 'Seal Stone Countertops (Annual Test)',
    description: 'Natural stone countertops like granite, marble, and soapstone may need periodic resealing. Do the water bead test annually — if water soaks in within 5 minutes, reseal.',
    instructions: [
      'Clean the countertop thoroughly with a pH-neutral stone cleaner',
      'Do the water bead test: sprinkle water on the surface — if it soaks in within 5 minutes, it needs resealing',
      'If resealing: make sure the surface is completely clean and dry',
      'Apply stone sealer with a clean cloth in small sections',
      'Let it absorb for 15-20 minutes (follow product instructions)',
      'Wipe off any excess sealer with a clean dry cloth',
      'Allow 24 hours to cure before heavy use',
    ],
    category: 'general',
    priority: 'low',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [4],
    estimated_minutes: 30,
    estimated_cost: 20,
    requires_countertop_type: ['granite', 'marble', 'soapstone'],
  },

  // ═══ BATHROOM & LAUNDRY (from Proventive) ═══
  {
    id: 'washing-machine-clean',
    title: 'Clean Washing Machine',
    description: 'Mold, mildew, and detergent residue build up inside your washer, causing odors and reducing cleaning performance. Deep clean monthly or quarterly.',
    instructions: [
      'Run an empty hot cycle with 2 cups of white vinegar',
      'Wipe down the rubber door gasket with a vinegar-soaked cloth (front-loaders)',
      'Pull out and scrub the detergent/softener dispenser tray',
      'Clean the lint/debris filter (usually at the bottom front of front-loaders)',
      'Wipe the exterior and control panel',
      'Leave the door open after each use to prevent mildew',
      'For top-loaders: clean around the agitator and the rim',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },
  {
    id: 'drain-clearing',
    title: 'Clear & Maintain Household Drains',
    description: 'Hair, soap scum, and grease accumulate in drains over time. Proactive cleaning prevents slow drains and costly clogs.',
    instructions: [
      'Remove drain covers and pull out any visible hair or debris',
      'Pour 1/2 cup baking soda followed by 1/2 cup vinegar into each drain',
      'Let it fizz for 15-30 minutes, then flush with boiling water',
      'Use a drain snake or zip tool on slow drains to pull out deeper clogs',
      'Clean pop-up stoppers in bathroom sinks (lift and wipe off buildup)',
      'For kitchen sinks: run hot water for 30 seconds after each use',
      'Install mesh drain covers to catch hair and food particles',
    ],
    category: 'plumbing',
    priority: 'medium',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'bathroom-exhaust-fan-clean',
    title: 'Clean Bathroom Exhaust Fans',
    description: 'Dust-clogged exhaust fans cannot properly remove moisture, leading to mold growth, peeling paint, and poor air quality.',
    instructions: [
      'Turn off the fan at the switch or breaker',
      'Remove the fan cover (usually pulls down and unclips)',
      'Soak the cover in warm soapy water and scrub gently',
      'Use a vacuum with a brush attachment to clean dust from the fan blades and housing',
      'Wipe the motor housing with a damp cloth (do not get the motor wet)',
      'Dry and reinstall the cover',
      'Test that the fan runs smoothly and moves air properly',
      'Hold a tissue near the fan — it should be pulled toward it when running',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'biannual',
    scheduling_type: 'dynamic',
    interval_days: 180,
    applicable_months: [4, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },

  // ═══ THROUGHOUT THE HOME (from Proventive) ═══
  {
    id: 'ceiling-fan-clean-reverse',
    title: 'Clean & Reverse Ceiling Fans',
    description: 'Dusty fan blades spread allergens. Reversing direction seasonally improves comfort — counterclockwise in summer (downdraft), clockwise in winter (updraft to circulate warm air).',
    instructions: [
      'Turn off the fan and let it stop completely',
      'Use a pillowcase over each blade to trap dust while wiping (prevents falling onto furniture)',
      'Wipe the motor housing and light fixtures',
      'Locate the direction switch on the fan body',
      'Set to COUNTERCLOCKWISE for summer (you should feel a breeze below)',
      'Set to CLOCKWISE for winter (pushes warm air from ceiling down the walls)',
      'Tighten any loose blade screws while you are up there',
    ],
    category: 'general',
    priority: 'low',
    frequency: 'biannual',
    scheduling_type: 'dynamic',
    interval_days: 180,
    applicable_months: [4, 10],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'lightbulb-check',
    title: 'Check & Replace Burned-Out Lightbulbs',
    description: 'Walk through your home and replace any burned-out or flickering bulbs. Upgrade to LED where possible — they last 25x longer and use 75% less energy.',
    instructions: [
      'Walk through every room and check each light fixture',
      'Note any burned-out, flickering, or dim bulbs',
      'Check exterior lights including porch, garage, and landscape lighting',
      'Replace with LED bulbs where possible (match wattage and base type)',
      'Verify correct color temperature: warm white (2700K) for living spaces, daylight (5000K) for task areas',
      'Check that dimmer switches are compatible with LED bulbs (not all are)',
      'Dispose of old CFLs at a recycling center (they contain mercury)',
    ],
    category: 'electrical',
    priority: 'low',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 15,
    estimated_cost: 10,
  },

  // ═══ HOME UTILITIES (from Proventive) ═══
  {
    id: 'winterize-ac-condenser',
    title: 'Winterize A/C Condenser Unit',
    description: 'Protect your outdoor AC unit from winter debris and ice damage. Covering and clearing around the unit extends its life.',
    instructions: [
      'Turn off power to the AC unit at the exterior disconnect or breaker',
      'Remove any leaves, sticks, and debris from around and on top of the unit',
      'Rinse the condenser fins gently with a hose to remove remaining dirt',
      'Allow the unit to dry completely',
      'Place a breathable condenser cover over the top (do NOT wrap entirely — trapped moisture causes corrosion)',
      'Or place a piece of plywood on top weighted with a brick to keep debris out',
      'Clear a 2-foot perimeter around the unit from shrubs and mulch',
      'Check periodically in winter and remove any ice dams or heavy snow',
    ],
    category: 'hvac',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [11],
    estimated_minutes: 15,
    estimated_cost: 0,
    requires_equipment: 'hvac',
    applicable_regions: ['north', 'mountain'],
  },
  {
    id: 'air-exchanger-clean',
    title: 'Clean & Maintain Air Exchanger (HRV/ERV)',
    description: 'Heat Recovery Ventilators and Energy Recovery Ventilators need regular filter cleaning to maintain indoor air quality and efficiency.',
    instructions: [
      'Turn off the unit before servicing',
      'Remove and inspect the filters — vacuum or wash with mild soap and water',
      'Clean the heat exchange core — remove, rinse with warm water, and let dry',
      'Vacuum dust from inside the unit cabinet',
      'Check condensate drain for clogs — flush with warm water',
      'Inspect outdoor intake and exhaust hoods for blockages (bird nests, snow, leaves)',
      'Reinstall filters and core once dry',
      'Turn the unit back on and verify airflow from the vents',
    ],
    category: 'hvac',
    priority: 'medium',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 25,
    estimated_cost: 0,
    applicable_regions: ['north', 'mountain'],
  },
  {
    id: 'water-softener-salt',
    title: 'Refill Water Softener Salt',
    description: 'Check salt level monthly and refill as needed. Low salt means hard water passes through, causing scale buildup on pipes, fixtures, and appliances.',
    instructions: [
      'Open the brine tank lid and check the salt level',
      'Salt should be at least 3-4 inches above the water line',
      'If low, add salt pellets (evaporated salt pellets are recommended over rock salt)',
      'Break up any salt bridges (hardened crust) with a broom handle',
      'Check for a salt mush buildup at the bottom — scoop out if present',
      'Verify the system is regenerating on schedule (check the control panel)',
      'Clean the brine tank annually — drain, scrub, and refill with fresh salt',
    ],
    category: 'plumbing',
    priority: 'medium',
    frequency: 'monthly',
    scheduling_type: 'dynamic',
    interval_days: 30,
    applicable_months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    estimated_minutes: 10,
    estimated_cost: 15,
    requires_home_feature: 'has_water_softener',
  },

  // ═══ OUTDOOR (from Proventive) ═══
  {
    id: 'garbage-bins-clean',
    title: 'Clean Garbage & Recycling Bins',
    description: 'Bacteria, odors, and pests thrive in dirty bins. A quarterly scrub keeps them sanitary and reduces attracting wildlife.',
    instructions: [
      'Roll bins to a driveway or concrete surface (not the lawn)',
      'Rinse the inside with a garden hose',
      'Spray with a mixture of dish soap, baking soda, and white vinegar',
      'Scrub the interior with a long-handled brush',
      'Rinse thoroughly and let air dry in the sun (UV kills bacteria)',
      'Sprinkle baking soda in the bottom to absorb future odors',
      'In hot months, consider double-bagging food waste to reduce maggot risk',
    ],
    category: 'outdoor',
    priority: 'low',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [3, 6, 9, 12],
    estimated_minutes: 15,
    estimated_cost: 0,
  },

  // ═══════════════════════════════════════════════════
  // REGION-SPECIFIC TASKS
  // ═══════════════════════════════════════════════════

  // ── South / Hot-Humid Region ──
  {
    id: 'south-termite-inspection',
    title: 'Schedule Annual Termite Inspection',
    description: 'Southern climates have year-round termite activity. An annual professional inspection catches infestations before structural damage occurs.',
    instructions: [
      'Schedule a licensed pest control company for a termite inspection',
      'Clear access to foundation walls, crawlspaces, and garage',
      'Check for mud tubes along foundation walls yourself beforehand',
      'Look for discarded wings near windows and doors',
      'Ask about preventive treatment options (bait stations or barrier treatment)',
      'Keep the inspection report for your records and future home sale',
    ],
    category: 'pest_control',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3, 4],
    estimated_minutes: 60,
    estimated_cost: 100,
    applicable_regions: ['south'],
  },
  {
    id: 'south-ac-drain-line',
    title: 'Flush AC Condensate Drain Line',
    description: 'Humid climates cause algae and mold to clog condensate lines. A clogged line can cause water damage, mold growth, and AC shutdowns.',
    instructions: [
      'Locate the condensate drain line (PVC pipe near your indoor AC unit)',
      'Pour 1 cup of distilled white vinegar into the drain line opening',
      'Wait 30 minutes, then flush with warm water',
      'Check the outdoor drain exit to verify water flows freely',
      'If slow, use a wet/dry vac on the outdoor end to clear the blockage',
      'Consider installing a drain line safety switch if you don\'t have one',
    ],
    category: 'hvac',
    priority: 'high',
    frequency: 'quarterly',
    scheduling_type: 'seasonal',
    applicable_months: [3, 6, 9],
    estimated_minutes: 15,
    estimated_cost: 0,
    requires_equipment: 'hvac',
    applicable_regions: ['south'],
  },
  {
    id: 'south-hurricane-prep',
    title: 'Hurricane Season Prep — Review Emergency Plan',
    description: 'Hurricane season runs June-November. Prepare your home and family before storms arrive.',
    instructions: [
      'Verify homeowner\'s insurance and flood coverage are current',
      'Test and stock emergency supplies: water, flashlights, batteries, first aid',
      'Trim trees and remove dead branches that could become projectiles',
      'Know where your main water shutoff and gas shutoff are located',
      'Secure or store outdoor furniture, grills, and patio items',
      'Take photos/video of your home\'s contents for insurance documentation',
      'Charge portable battery packs and ensure generator fuel is fresh',
    ],
    category: 'seasonal',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [5, 6],
    estimated_minutes: 60,
    estimated_cost: 0,
    applicable_regions: ['south', 'coastal'],
  },
  {
    id: 'south-mold-check',
    title: 'Check for Mold in Humid Areas',
    description: 'High humidity promotes mold growth in bathrooms, under sinks, and in crawlspaces. Catching it early prevents health issues and expensive remediation.',
    instructions: [
      'Inspect under all bathroom and kitchen sinks for moisture or discoloration',
      'Check behind toilets and around tub/shower caulking',
      'Look for dark spots on ceiling tiles and around AC vents',
      'If you have a crawlspace, check for standing water or moisture on joists',
      'Ensure bathroom exhaust fans vent outside (not into the attic)',
      'Run a dehumidifier in damp areas — aim for 30-50% indoor humidity',
    ],
    category: 'general',
    priority: 'medium',
    frequency: 'biannual',
    scheduling_type: 'seasonal',
    applicable_months: [5, 10],
    estimated_minutes: 30,
    estimated_cost: 0,
    applicable_regions: ['south', 'coastal'],
  },

  // ── North / Cold Region ──
  {
    id: 'north-winterize-pipes',
    title: 'Winterize Outdoor Plumbing',
    description: 'Frozen pipes are the most common cause of winter water damage. Properly winterizing prevents burst pipes and thousands in repairs.',
    instructions: [
      'Disconnect and drain all garden hoses',
      'Shut off interior valves that supply outdoor hose bibs',
      'Open outdoor hose bibs to drain remaining water',
      'Install insulated covers on all outdoor faucets',
      'Insulate any exposed pipes in unheated areas (garage, crawlspace, attic)',
      'Know where your main water shutoff is in case of emergency',
      'Set thermostat no lower than 55°F when away',
    ],
    category: 'plumbing',
    priority: 'urgent',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [10, 11],
    estimated_minutes: 45,
    estimated_cost: 20,
    applicable_regions: ['north', 'mountain', 'midwest'],
  },
  {
    id: 'north-ice-dam-prevention',
    title: 'Prevent Ice Dams — Check Attic Insulation & Ventilation',
    description: 'Ice dams form when warm attic air melts roof snow that refreezes at the eaves. They cause water to back up under shingles and into your home.',
    instructions: [
      'Check attic insulation depth — aim for R-38 to R-60 (10-14 inches of blown-in)',
      'Seal air leaks around attic access doors, plumbing stacks, and wiring',
      'Verify soffit vents are not blocked by insulation',
      'Ensure ridge vent or gable vents provide adequate airflow',
      'After heavy snow, use a roof rake to clear the first 3 feet from eaves',
      'Never chip ice off gutters — you\'ll damage them',
    ],
    category: 'roof',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [10, 11],
    estimated_minutes: 30,
    estimated_cost: 0,
    applicable_regions: ['north', 'mountain'],
  },
  {
    id: 'north-furnace-carbon-monoxide',
    title: 'Test Carbon Monoxide Detectors Before Heating Season',
    description: 'CO is odorless and deadly. Furnaces, water heaters, and fireplaces are common sources. Test all detectors before you start running heat.',
    instructions: [
      'Press the test button on every CO detector in your home',
      'Replace batteries if the test chirp is weak',
      'Replace any detector older than 5-7 years (check the manufacture date on back)',
      'Ensure there\'s a CO detector on every level and near sleeping areas',
      'If you have a fuel-burning appliance, there must be a detector within 15 feet',
    ],
    category: 'safety',
    priority: 'urgent',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [9, 10],
    estimated_minutes: 10,
    estimated_cost: 0,
    applicable_regions: ['north', 'mountain', 'midwest'],
  },
  {
    id: 'north-spring-frost-heave',
    title: 'Inspect for Winter Frost Heave Damage',
    description: 'Freeze-thaw cycles shift concrete, crack foundations, and pop fence posts. Spring is the time to catch and repair damage before it worsens.',
    instructions: [
      'Walk your property and check driveway, walkways, and patio for new cracks or heaving',
      'Inspect foundation walls for new cracks (mark them with tape to monitor)',
      'Check fence posts — push each one to see if it\'s loose',
      'Look at deck posts and stairs for shifting',
      'Re-level any settled pavers or stepping stones',
      'Fill concrete cracks with appropriate sealant before they grow',
    ],
    category: 'outdoor',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3, 4],
    estimated_minutes: 30,
    estimated_cost: 0,
    applicable_regions: ['north', 'mountain', 'midwest'],
  },

  // ── Desert / Arid Region ──
  {
    id: 'desert-evap-cooler-startup',
    title: 'Start Up Evaporative Cooler (Swamp Cooler)',
    description: 'Evaporative coolers need spring startup — reconnect water, replace pads, and oil the motor. Neglecting this shortens the unit\'s life.',
    instructions: [
      'Remove the winter cover',
      'Connect the water supply line and check for leaks',
      'Replace evaporative pads (do this annually)',
      'Oil the motor and blower bearings with 3-in-1 oil',
      'Turn on the water pump and let pads saturate for 15 minutes before starting the fan',
      'Check the float valve — adjust so water is 1 inch below the overflow',
      'Clean the water reservoir of mineral deposits',
    ],
    category: 'hvac',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [4, 5],
    estimated_minutes: 45,
    estimated_cost: 30,
    applicable_regions: ['desert', 'mountain'],
  },
  {
    id: 'desert-monsoon-prep',
    title: 'Monsoon Season Prep — Drainage & Roof Check',
    description: 'Desert monsoons bring intense flash flooding and wind damage. Prepare your property before the season starts.',
    instructions: [
      'Clear all drainage channels and yard drains of debris',
      'Check roof for loose tiles, cracked sealant, or damaged flashing',
      'Ensure downspouts direct water at least 6 feet from foundation',
      'Trim desert trees (palo verde, mesquite) of dead or crossing branches',
      'Secure patio furniture, shade sails, and trash cans',
      'Check your sump pump if applicable',
      'Verify homeowner\'s insurance covers flood damage',
    ],
    category: 'seasonal',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [6],
    estimated_minutes: 45,
    estimated_cost: 0,
    applicable_regions: ['desert'],
  },

  // ── Coastal Region ──
  {
    id: 'coastal-salt-air-rinse',
    title: 'Rinse Exterior for Salt Air Corrosion',
    description: 'Salt air corrodes metal fixtures, hinges, and outdoor equipment. Regular rinsing slows the damage significantly.',
    instructions: [
      'Rinse all exterior metal surfaces with fresh water — door hinges, railings, light fixtures',
      'Pay extra attention to outdoor AC units — salt buildup reduces efficiency',
      'Lubricate exterior hinges and locks with a silicone-based spray (not WD-40)',
      'Check for rust forming on outdoor furniture and treat early',
      'Rinse outdoor grills and smokers',
      'Consider protective coatings or covers for high-value equipment',
    ],
    category: 'outdoor',
    priority: 'medium',
    frequency: 'quarterly',
    scheduling_type: 'seasonal',
    applicable_months: [3, 6, 9, 12],
    estimated_minutes: 30,
    estimated_cost: 0,
    applicable_regions: ['coastal'],
  },
  {
    id: 'coastal-window-seal-check',
    title: 'Inspect Window and Door Seals for Salt Damage',
    description: 'Coastal homes take a beating from salt spray and wind-driven rain. Deteriorated seals lead to water infiltration and mold.',
    instructions: [
      'Check all window caulking for cracks or gaps',
      'Inspect door weatherstripping — press a dollar bill in the closed door, if it pulls out easily the seal is worn',
      'Look for water stains or discoloration around window frames inside',
      'Check sliding door tracks for salt buildup and clean with vinegar solution',
      'Re-caulk any failed joints with exterior-grade silicone caulk',
      'Consider storm shutters if you\'re in a hurricane zone',
    ],
    category: 'general',
    priority: 'medium',
    frequency: 'biannual',
    scheduling_type: 'seasonal',
    applicable_months: [4, 10],
    estimated_minutes: 45,
    estimated_cost: 15,
    applicable_regions: ['coastal'],
  },

  // ── Midwest Region ──
  {
    id: 'midwest-tornado-prep',
    title: 'Tornado Season Prep — Review Emergency Plan',
    description: 'Tornado season peaks March-June in the Midwest. Have a plan before severe weather hits.',
    instructions: [
      'Identify your interior safe room (basement, interior closet, or bathroom on lowest floor)',
      'Stock the safe room with flashlights, batteries, first aid kit, and shoes',
      'Practice the plan with your family — especially kids',
      'Sign up for local emergency alerts (most counties have text/app alerts)',
      'Know the difference: WATCH = conditions favorable, WARNING = take shelter NOW',
      'Take a home inventory video for insurance — store it in the cloud',
      'Trim dead tree branches that could become projectiles',
    ],
    category: 'seasonal',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3],
    estimated_minutes: 30,
    estimated_cost: 0,
    applicable_regions: ['midwest', 'south'],
  },
  {
    id: 'midwest-sump-pump-test',
    title: 'Test Sump Pump Before Spring Thaw',
    description: 'Spring snowmelt and rain saturate the soil. A failed sump pump means a flooded basement. Test it before you need it.',
    instructions: [
      'Pour 5 gallons of water into the sump pit slowly',
      'The pump should kick on, remove the water, and shut off automatically',
      'If it doesn\'t start, check the power outlet and circuit breaker',
      'Listen for unusual sounds — grinding or rattling means worn bearings',
      'Check the discharge pipe outside — ensure it\'s not frozen or clogged',
      'Test the backup battery system if you have one',
      'Consider a water alarm in the pit as an extra safeguard',
    ],
    category: 'plumbing',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [2, 3],
    estimated_minutes: 15,
    estimated_cost: 0,
    applicable_regions: ['midwest', 'north'],
  },

  // ═══ NEW TASKS ═══
  {
    id: 'gfci-outlet-test',
    title: 'Test GFCI Outlets',
    description: 'GFCI outlets protect against electrical shock in wet areas. Press the Test button, verify power cuts off, then press Reset. Replace any that fail.',
    instructions: [
      'Locate all GFCI outlets — typically in kitchen, bathrooms, garage, outdoor, and laundry',
      'Plug in a nightlight or phone charger to verify the outlet has power',
      'Press the TEST button on the outlet — the device should lose power',
      'Press the RESET button to restore power',
      'If the outlet does not trip or reset, it needs to be replaced',
      'Check the manufacture date — GFCI outlets should be replaced every 10-15 years',
    ],
    category: 'electrical',
    priority: 'high',
    frequency: 'quarterly',
    scheduling_type: 'dynamic',
    interval_days: 90,
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 10,
    estimated_cost: 0,
  },
  {
    id: 'water-pressure-check',
    title: 'Check Water Pressure',
    description: 'Water pressure above 80 PSI damages pipes, fixtures, and appliances over time. Use a gauge on an outdoor spigot to test. Install a pressure regulator if consistently high.',
    instructions: [
      'Buy or borrow a water pressure gauge (available at hardware stores for $10)',
      'Attach the gauge to an outdoor hose bib or laundry faucet',
      'Make sure no water is running anywhere in the house',
      'Turn on the faucet fully and read the gauge',
      'Ideal pressure is 40-60 PSI. Acceptable range is 30-80 PSI',
      'If above 80 PSI, install a pressure reducing valve (PRV) or adjust existing one',
      'If below 30 PSI, check for leaks or contact your water utility',
    ],
    category: 'plumbing',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'dynamic',
    interval_days: 365,
    applicable_months: [4],
    estimated_minutes: 10,
    estimated_cost: 10,
  },
  {
    id: 'midwest-storm-shelter-check',
    title: 'Storm Shelter & Emergency Kit Check',
    description: 'Before tornado season, verify your storm shelter is accessible and your emergency kit is stocked with fresh supplies.',
    instructions: [
      'Check shelter door or access point opens easily',
      'Verify flashlights have fresh batteries',
      'Check that bottled water is not expired (replace annually)',
      'Confirm first aid kit is stocked',
      'Ensure weather radio has fresh batteries or is charged',
      'Store sturdy shoes, a blanket, and important documents in the shelter',
      'Review your family emergency plan and meeting point',
    ],
    category: 'safety',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [3],
    estimated_minutes: 20,
    estimated_cost: 0,
    applicable_regions: ['midwest', 'south'],
  },
  {
    id: 'caulk-windows-doors',
    title: 'Inspect & Recaulk Windows and Doors',
    description: 'Cracked or missing caulk around windows and doors lets in drafts, moisture, and insects. Check annually in fall before heating season.',
    instructions: [
      'Walk the exterior and inspect caulking around every window and door frame',
      'Look for cracks, gaps, shrinking, or peeling caulk',
      'Remove old failing caulk with a utility knife or caulk removal tool',
      'Clean the surface and let it dry',
      'Apply exterior-grade silicone or polyurethane caulk in a smooth bead',
      'Also check interior caulk around bathtubs, showers, and countertops',
      'Smooth the bead with a wet finger or caulk tool',
    ],
    category: 'general',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [9, 10],
    estimated_minutes: 60,
    estimated_cost: 15,
  },
  // ═══ SUMMER TASKS (filling June/July/August gaps) ═══
  {
    id: 'inspect-irrigation-sprinkler',
    title: 'Inspect & Adjust Sprinkler Heads',
    description: 'Walk each zone while it runs. Straighten or replace tilted/broken heads, clear clogs, and adjust spray patterns to avoid watering sidewalks or the house.',
    instructions: [
      'Run each irrigation zone one at a time',
      'Walk the zone while it runs — look for broken, tilted, or clogged heads',
      'Straighten any leaning heads and clear debris from nozzles',
      'Adjust spray patterns so water hits the lawn, not sidewalks or siding',
      'Check for pooling or dry spots — may need a new head or adjusted run time',
      'Inspect the backflow preventer for leaks',
    ],
    category: 'outdoor',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [6],
    estimated_minutes: 30,
    estimated_cost: 0,
    requires_home_feature: 'has_sprinkler_system',
  },
  {
    id: 'deep-clean-outdoor-furniture',
    title: 'Deep Clean Outdoor Furniture & Cushions',
    description: 'Remove mildew, pollen, and grime from patio furniture at the start of summer. Clean cushion covers in the wash and scrub frames with soapy water.',
    instructions: [
      'Remove all cushion covers and machine-wash if care label allows',
      'For non-washable cushions, spray with a 50/50 vinegar-water solution and scrub with a brush',
      'Hose down metal, wicker, or plastic frames',
      'Scrub frames with dish soap and water using a soft brush',
      'Rinse thoroughly and let everything dry completely in the sun',
      'Apply protectant spray to wicker or wood furniture',
    ],
    category: 'deck',
    priority: 'low',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [6],
    estimated_minutes: 45,
    estimated_cost: 5,
    requires_home_feature: 'has_deck',
  },
  {
    id: 'inspect-exterior-paint-siding',
    title: 'Inspect Exterior Paint & Siding',
    description: 'Walk the perimeter of your home looking for peeling paint, cracked siding, or gaps. Catching damage early prevents water intrusion and costly repairs.',
    instructions: [
      'Walk the full perimeter of the house, looking at all sides',
      'Check for peeling, bubbling, or cracking paint',
      'Look for cracked, warped, or loose siding panels',
      'Inspect where different materials meet (e.g., siding to trim, around windows)',
      'Check the foundation/siding junction for gaps or cracks',
      'Note any areas with mold, mildew, or discoloration',
      'Schedule touch-up painting or siding repair before fall',
    ],
    category: 'general',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [7],
    estimated_minutes: 30,
    estimated_cost: 0,
  },
  {
    id: 'clean-dryer-vent-duct',
    title: 'Clean Dryer Vent & Exhaust Duct',
    description: 'Lint buildup in the dryer vent is a top cause of house fires. Disconnect the duct and clean it thoroughly at least once a year.',
    instructions: [
      'Unplug the dryer (or turn off gas valve for gas dryers)',
      'Pull the dryer away from the wall and disconnect the exhaust duct',
      'Use a dryer vent brush kit to clean inside the duct',
      'Also clean the vent opening on the exterior of the house',
      'Remove lint from the dryer exhaust port where the duct connects',
      'Reconnect the duct with foil tape (not screws, which catch lint)',
      'Push the dryer back and plug it in — run a test cycle',
    ],
    category: 'appliance',
    priority: 'high',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [7],
    estimated_minutes: 30,
    estimated_cost: 15,
  },
  {
    id: 'check-attic-ventilation',
    title: 'Check Attic Ventilation & Insulation',
    description: 'Hot summer days reveal attic ventilation problems. Check that vents are clear, insulation is intact, and there are no signs of moisture or pests.',
    instructions: [
      'Go into the attic during the morning (before peak heat)',
      'Check that soffit vents and ridge vents are not blocked by insulation',
      'Look for daylight coming through the roof — could indicate gaps',
      'Check insulation depth — should be at least 10-14 inches for R-38',
      'Look for signs of pests: droppings, nesting material, chewed wires',
      'Check for any moisture stains or mold on the underside of roof sheathing',
      'Verify the attic fan (if installed) is running properly',
    ],
    category: 'general',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [7, 8],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'inspect-driveway-walkways',
    title: 'Inspect & Repair Driveway and Walkways',
    description: 'Summer is ideal for concrete and asphalt repairs. Fill cracks before they grow and seal-coat asphalt driveways to extend their life.',
    instructions: [
      'Walk your driveway and all concrete walkways',
      'Mark any cracks wider than 1/4 inch',
      'Clean cracks with a pressure washer or stiff brush',
      'Fill small cracks with concrete caulk or asphalt crack filler',
      'For asphalt driveways, apply a seal coat every 2-3 years',
      'Check for heaving, settling, or trip hazards — may need professional repair',
      'Remove weeds growing through cracks before filling',
    ],
    category: 'general',
    priority: 'low',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [8],
    estimated_minutes: 60,
    estimated_cost: 25,
  },
  {
    id: 'mid-summer-lawn-care',
    title: 'Mid-Summer Lawn Health Check',
    description: 'Check for brown patches, grub damage, and irrigation coverage. Adjust mowing height for summer heat and address any bare spots.',
    instructions: [
      'Walk the lawn and look for brown or dead patches',
      'Pull on brown grass — if it lifts easily like a carpet, you have grubs',
      'Check for fungal disease: circular brown patches with a dark ring',
      'Raise mowing height to 3-4 inches in summer heat',
      'Water deeply but infrequently — 1 inch per week, preferably early morning',
      'Apply grub treatment if damage is found (late July is ideal timing)',
      'Avoid fertilizing in extreme heat — wait for early fall',
    ],
    category: 'lawn',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [7, 8],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'inspect-deck-stain-seal',
    title: 'Inspect Deck & Reseal if Needed',
    description: 'Sprinkle water on your deck boards. If it soaks in instead of beading up, the seal has worn off and it\'s time to reseal.',
    instructions: [
      'Sprinkle water on several deck boards in different areas',
      'If water beads up, the existing seal is still good',
      'If water soaks in quickly, the deck needs resealing',
      'Inspect boards for cracks, splitting, warping, or soft spots',
      'Check that deck railing is secure — push test each section',
      'Look under the deck for signs of rot or pest damage',
      'If resealing, clean the deck first with a deck cleaner and let dry 48 hours',
    ],
    category: 'deck',
    priority: 'medium',
    frequency: 'annual',
    scheduling_type: 'seasonal',
    applicable_months: [6, 7],
    estimated_minutes: 20,
    estimated_cost: 0,
    requires_home_feature: 'has_deck',
  },
];

// ─── Get tasks applicable for a given month, optionally filtered by region ───
export const getTasksForMonth = (
  month: number,
  homeFeatures: Record<string, any>,
  state?: string
): TaskTemplate[] => {
  const region = getClimateRegion(state);
  return TASK_TEMPLATES.filter((task) => {
    if (!task.applicable_months.includes(month)) return false;
    if (task.requires_home_feature && !homeFeatures[task.requires_home_feature]) return false;
    // Region filter: if task has applicable_regions, check if homeowner's region matches
    if (task.applicable_regions && !task.applicable_regions.includes('all')) {
      if (!task.applicable_regions.includes(region)) return false;
    }
    return true;
  });
};

// ─── Equipment categories with display info ───
export const EQUIPMENT_CATEGORIES = [
  { id: 'hvac', label: 'HVAC / Air Conditioning', icon: 'thermometer', color: '#2196F3' },
  { id: 'water_heater', label: 'Water Heater', icon: 'flame', color: '#FF9800' },
  { id: 'roof', label: 'Roof & Gutters', icon: 'home', color: '#795548' },
  { id: 'plumbing', label: 'Plumbing', icon: 'water', color: '#00BCD4' },
  { id: 'electrical', label: 'Electrical', icon: 'flash', color: '#FFC107' },
  { id: 'appliance', label: 'Appliances', icon: 'settings', color: '#607D8B' },
  { id: 'outdoor', label: 'Outdoor', icon: 'leaf', color: '#8BC34A' },
  { id: 'safety', label: 'Safety Systems', icon: 'shield-checkmark', color: '#E53935' },
  { id: 'pool', label: 'Pool & Hot Tub', icon: 'water', color: '#03A9F4' },
  { id: 'garage', label: 'Garage', icon: 'car', color: '#9E9E9E' },
] as const;
