// ═══════════════════════════════════════════════════════════════
// Canopy Maintenance Engine — Task Templates & Seasonal Logic
// ═══════════════════════════════════════════════════════════════
import type { TaskFrequency, TaskPriority, EquipmentCategory } from '@/types';

export interface TaskTemplate {
  id: string;
  title: string;
  description: string;
  instructions: string[];
  category: EquipmentCategory | 'general' | 'lawn' | 'pool' | 'deck' | 'seasonal';
  priority: TaskPriority;
  frequency: TaskFrequency;
  applicable_months: number[];
  estimated_minutes: number;
  estimated_cost: number;
  requires_equipment?: EquipmentCategory;
  requires_home_feature?: string; // e.g., 'has_pool', 'has_deck'
}

// ─── Monthly & Seasonal Task Templates ───
export const TASK_TEMPLATES: TaskTemplate[] = [
  // ═══ HVAC ═══
  {
    id: 'hvac-filter-change',
    title: 'Replace HVAC Air Filters',
    description: 'Dirty filters restrict airflow, increase energy bills, and reduce air quality. Replace every 1-3 months depending on filter type.',
    instructions: [
      'Turn off your HVAC system',
      'Locate the filter(s) — usually near the return air vent or inside the air handler',
      'Note the filter size printed on the frame (e.g., 20x25x1)',
      'Slide out the old filter and check the airflow direction arrow',
      'Insert the new filter with the arrow pointing toward the blower',
      'Turn the system back on',
    ],
    category: 'hvac',
    priority: 'high',
    frequency: 'monthly',
    applicable_months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    estimated_minutes: 10,
    estimated_cost: 15,
    requires_equipment: 'hvac',
  },
  {
    id: 'hvac-spring-tuneup',
    title: 'Schedule Spring AC Tune-Up',
    description: 'Annual professional AC maintenance before summer. Catches issues early and improves efficiency by up to 15%.',
    instructions: [
      'Call your HVAC service provider to schedule a tune-up',
      'Ensure they check refrigerant levels, clean coils, and test the thermostat',
      'Clear at least 2 feet around the outdoor condenser unit',
      'Replace your air filter before they arrive',
    ],
    category: 'hvac',
    priority: 'high',
    frequency: 'annual',
    applicable_months: [3, 4],
    estimated_minutes: 90,
    estimated_cost: 150,
    requires_equipment: 'hvac',
  },
  {
    id: 'hvac-fall-furnace',
    title: 'Schedule Fall Furnace Tune-Up',
    description: 'Annual furnace inspection before heating season. Ensures safe operation and catches carbon monoxide risks.',
    instructions: [
      'Schedule a professional furnace inspection',
      'Replace the air filter',
      'Test your thermostat — switch to heat mode and verify it kicks on',
      'Check for unusual noises or smells when the furnace first starts',
      'Ensure CO detectors near the furnace are working',
    ],
    category: 'hvac',
    priority: 'high',
    frequency: 'annual',
    applicable_months: [9, 10],
    estimated_minutes: 60,
    estimated_cost: 120,
    requires_equipment: 'hvac',
  },

  // ═══ WATER HEATER ═══
  {
    id: 'water-heater-flush',
    title: 'Flush Water Heater',
    description: 'Sediment buildup reduces efficiency and shortens tank life. Annual flushing removes buildup and keeps your water heater running efficiently.',
    instructions: [
      'Turn off the water heater (gas: pilot setting; electric: breaker off)',
      'Connect a garden hose to the drain valve at the bottom',
      'Run the hose to a drain or outside',
      'Open the drain valve and let water flow until it runs clear (5-10 minutes)',
      'Close the drain valve and turn the water supply back on',
      'Once the tank is full, turn the heater back on',
    ],
    category: 'water_heater',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [4, 10],
    estimated_minutes: 30,
    estimated_cost: 0,
    requires_equipment: 'water_heater',
  },
  {
    id: 'water-heater-anode-rod',
    title: 'Check Anode Rod',
    description: 'The sacrificial anode rod prevents tank corrosion. If it is more than 50% corroded, replace it to extend your water heater life by years.',
    instructions: [
      'Locate the anode rod — typically on top of the water heater',
      'Use a 1-1/16" socket wrench to unscrew it',
      'Pull it out and inspect — if less than 1/2" thick or coated in calcium, replace it',
      'New rods cost $20-50 and take 10 minutes to swap',
    ],
    category: 'water_heater',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [4],
    estimated_minutes: 20,
    estimated_cost: 30,
    requires_equipment: 'water_heater',
  },

  // ═══ ROOF & GUTTERS ═══
  {
    id: 'gutter-clean-spring',
    title: 'Clean Gutters (Spring)',
    description: 'Remove debris from winter and spring pollen. Clogged gutters cause water damage to fascia, foundation, and landscaping.',
    instructions: [
      'Use a sturdy ladder with a stabilizer bar',
      'Wear gloves and scoop debris from each gutter section',
      'Flush gutters with a hose to check drainage',
      'Check downspouts for clogs — tap them and listen for hollow sound',
      'Ensure downspout extensions direct water 4-6 feet from the foundation',
      'Inspect gutter hangers and resecure any loose sections',
    ],
    category: 'roof',
    priority: 'high',
    frequency: 'biannual',
    applicable_months: [4, 5],
    estimated_minutes: 60,
    estimated_cost: 0,
  },
  {
    id: 'gutter-clean-fall',
    title: 'Clean Gutters (Fall)',
    description: 'Clear leaves before winter. Ice dams form when clogged gutters prevent drainage.',
    instructions: [
      'Wait until most leaves have fallen before cleaning',
      'Remove all debris from gutters and downspouts',
      'Flush with water to verify proper drainage',
      'Check for any damage or sagging sections',
      'Consider gutter guards if leaf buildup is severe',
    ],
    category: 'roof',
    priority: 'high',
    frequency: 'biannual',
    applicable_months: [11],
    estimated_minutes: 60,
    estimated_cost: 0,
  },
  {
    id: 'roof-inspection',
    title: 'Visual Roof Inspection',
    description: 'Look for damaged, missing, or curling shingles. Catching issues early prevents leaks and expensive repairs.',
    instructions: [
      'Use binoculars from the ground — no need to climb on the roof',
      'Look for missing, cracked, or curling shingles',
      'Check flashing around chimneys, vents, and skylights',
      'Look for dark streaks (algae) or moss growth',
      'Check inside your attic for daylight, water stains, or sagging',
      'If you spot issues, call a roofer for a professional inspection',
    ],
    category: 'roof',
    priority: 'medium',
    frequency: 'biannual',
    applicable_months: [4, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },

  // ═══ SAFETY ═══
  {
    id: 'smoke-co-test',
    title: 'Test Smoke & CO Detectors',
    description: 'Press the test button on every smoke and carbon monoxide detector in your home. Replace batteries annually.',
    instructions: [
      'Press and hold the test button on each detector',
      'It should beep loudly within a few seconds',
      'If the beep is weak or absent, replace the battery',
      'Replace the entire unit if it is more than 10 years old',
      'Ensure detectors are on every level and near bedrooms',
    ],
    category: 'safety',
    priority: 'high',
    frequency: 'monthly',
    applicable_months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    estimated_minutes: 10,
    estimated_cost: 0,
  },
  {
    id: 'fire-extinguisher-check',
    title: 'Check Fire Extinguishers',
    description: 'Verify the pressure gauge is in the green zone and the unit is accessible. Replace if expired.',
    instructions: [
      'Check the pressure gauge — needle should be in the green zone',
      'Verify the pin and tamper seal are intact',
      'Look for visible damage, rust, or dents',
      'Ensure it is easily accessible (kitchen, garage, workshop)',
      'Replace if more than 12 years old or if the gauge shows low pressure',
    ],
    category: 'safety',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [1],
    estimated_minutes: 5,
    estimated_cost: 0,
  },

  // ═══ PLUMBING ═══
  {
    id: 'winterize-hose-bibs',
    title: 'Winterize Hose Bibs',
    description: 'Disconnect hoses and shut off exterior water supply before the first freeze to prevent burst pipes.',
    instructions: [
      'Disconnect all garden hoses from outdoor faucets',
      'Drain any remaining water from the hoses and store them',
      'If you have interior shutoff valves for outdoor faucets, close them',
      'Open the outdoor faucet to drain any trapped water',
      'Install insulated hose bib covers on each outdoor faucet',
      'If you have a sprinkler system, have it professionally blown out',
    ],
    category: 'plumbing',
    priority: 'urgent',
    frequency: 'annual',
    applicable_months: [10, 11],
    estimated_minutes: 20,
    estimated_cost: 10,
  },
  {
    id: 'check-for-leaks',
    title: 'Check for Water Leaks',
    description: 'Inspect under sinks, around toilets, and near the water heater for drips or moisture. Small leaks become big problems fast.',
    instructions: [
      'Check under every sink for drips or moisture',
      'Look around the base of each toilet',
      'Inspect the water heater area for puddles',
      'Check the washing machine hoses for bulging or cracks',
      'Look at ceilings for water stains (sign of a leak above)',
      'Check your water meter — if it moves when all faucets are off, you have a leak',
    ],
    category: 'plumbing',
    priority: 'medium',
    frequency: 'quarterly',
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },

  // ═══ EXTERIOR ═══
  {
    id: 'dryer-vent-clean',
    title: 'Clean Dryer Vent',
    description: 'Lint buildup in dryer vents is a leading cause of house fires. Clean annually or more often if you notice longer drying times.',
    instructions: [
      'Pull the dryer away from the wall and disconnect the vent hose',
      'Use a dryer vent brush kit to clean inside the vent duct',
      'Clean the vent from the outside too — remove the exterior cover and brush out',
      'Check the vent flap moves freely and is not blocked by debris',
      'Reconnect everything and push the dryer back',
      'Run a test cycle to verify proper airflow',
    ],
    category: 'appliance',
    priority: 'high',
    frequency: 'annual',
    applicable_months: [3],
    estimated_minutes: 30,
    estimated_cost: 0,
  },
  {
    id: 'garage-door-maintenance',
    title: 'Garage Door Maintenance',
    description: 'Lubricate moving parts and test safety features. A well-maintained garage door lasts 15-30 years.',
    instructions: [
      'Spray silicone lubricant on hinges, rollers, and tracks',
      'Test the auto-reverse by placing a 2x4 under the door',
      'Test the photoelectric sensors by breaking the beam during closing',
      'Tighten any loose bolts on the track brackets',
      'Check the weatherstripping at the bottom for cracks',
      'Listen for grinding or scraping — may indicate worn rollers',
    ],
    category: 'garage',
    priority: 'medium',
    frequency: 'biannual',
    applicable_months: [4, 10],
    estimated_minutes: 20,
    estimated_cost: 5,
  },

  // ═══ LAWN & LANDSCAPE ═══
  {
    id: 'spring-lawn-care',
    title: 'Spring Lawn Care',
    description: 'Rake, dethatch if needed, apply pre-emergent herbicide, and start mowing when grass reaches 3-4 inches.',
    instructions: [
      'Rake to remove dead grass and leaves',
      'Apply pre-emergent herbicide before soil temp reaches 55°F',
      'Overseed any bare or thin spots',
      'Begin mowing when grass is actively growing (3-4 inches)',
      'Set mower height to the tallest recommended setting for your grass type',
      'Apply a slow-release fertilizer if your lawn has not been fed since fall',
    ],
    category: 'lawn',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [3, 4],
    estimated_minutes: 120,
    estimated_cost: 40,
  },
  {
    id: 'fall-lawn-care',
    title: 'Fall Lawn Care',
    description: 'Aerate, overseed, and apply fall fertilizer. This is the most impactful time to feed your lawn.',
    instructions: [
      'Aerate your lawn (rent an aerator or hire a pro)',
      'Overseed with appropriate grass seed for your lawn type',
      'Apply fall fertilizer — this is the most important feeding of the year',
      'Continue mowing until grass stops growing',
      'Lower mower height on the final cut of the season',
      'Remove fallen leaves — they smother grass if left over winter',
    ],
    category: 'lawn',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [9, 10],
    estimated_minutes: 180,
    estimated_cost: 60,
  },
  {
    id: 'tree-inspection',
    title: 'Inspect Trees & Prune',
    description: 'Look for dead branches, disease, and structural issues. Prune deciduous trees in late winter while dormant.',
    instructions: [
      'Walk around each tree and look up for dead or hanging branches',
      'Check trunks for cracks, cavities, or fungal growth',
      'Look for branches touching or near the house or power lines',
      'Prune dead/diseased branches at the collar (do not leave stubs)',
      'For large trees (>15 ft), hire a certified arborist',
      'Mulch around tree bases — 2-4 inches, kept 6 inches from the trunk',
    ],
    category: 'lawn',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [2, 3],
    estimated_minutes: 60,
    estimated_cost: 0,
  },

  // ═══ POOL ═══
  {
    id: 'pool-opening',
    title: 'Open Pool for Season',
    description: 'Remove cover, clean, balance chemicals, and start the filter system.',
    instructions: [
      'Remove and clean the pool cover',
      'Remove any winterizing plugs from return lines',
      'Reconnect the pump and filter system',
      'Fill the pool to the proper water level',
      'Run the pump and check for leaks',
      'Test and balance water chemistry (pH: 7.2-7.6, chlorine: 1-3 ppm)',
      'Vacuum and brush the pool walls and floor',
    ],
    category: 'pool',
    priority: 'high',
    frequency: 'annual',
    applicable_months: [4, 5],
    estimated_minutes: 180,
    estimated_cost: 100,
    requires_home_feature: 'has_pool',
  },
  {
    id: 'pool-weekly',
    title: 'Weekly Pool Maintenance',
    description: 'Skim, vacuum, test chemicals, clean skimmer baskets. Consistent weekly care prevents expensive problems.',
    instructions: [
      'Skim the surface for leaves and debris',
      'Empty skimmer and pump baskets',
      'Test water chemistry (pH, chlorine, alkalinity)',
      'Add chemicals as needed to maintain proper balance',
      'Vacuum the pool floor',
      'Brush walls and tile line',
      'Check filter pressure — clean or backwash if 8-10 PSI above normal',
    ],
    category: 'pool',
    priority: 'high',
    frequency: 'monthly',
    applicable_months: [5, 6, 7, 8, 9],
    estimated_minutes: 30,
    estimated_cost: 20,
    requires_home_feature: 'has_pool',
  },

  // ═══ DECK ═══
  {
    id: 'deck-spring-clean',
    title: 'Spring Deck Cleaning & Inspection',
    description: 'Power wash, inspect for damage, and apply sealer/stain if needed. A maintained deck lasts 25+ years.',
    instructions: [
      'Sweep the deck thoroughly',
      'Power wash with a fan tip (not a zero-degree tip — it can damage wood)',
      'Inspect for loose boards, popped nails, or splintering',
      'Check the ledger board connection to the house',
      'Look underneath for rot, insect damage, or structural issues',
      'If the deck fails the water bead test, plan to reseal/stain',
    ],
    category: 'deck',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [4, 5],
    estimated_minutes: 120,
    estimated_cost: 0,
    requires_home_feature: 'has_deck',
  },
  {
    id: 'deck-seal-stain',
    title: 'Seal or Stain Deck',
    description: 'Apply deck sealer or stain every 2-3 years to protect against moisture, UV, and wear.',
    instructions: [
      'Clean the deck thoroughly first (power wash 1-2 days before)',
      'Ensure the deck is completely dry (48 hours of dry weather)',
      'Apply deck cleaner/brightener if needed',
      'Use a pump sprayer, roller, or brush to apply stain/sealer',
      'Work in manageable sections, maintaining a wet edge',
      'Apply a second coat if recommended by the product',
      'Allow 24-48 hours to dry before foot traffic',
    ],
    category: 'deck',
    priority: 'medium',
    frequency: 'as_needed',
    applicable_months: [5, 6, 9],
    estimated_minutes: 240,
    estimated_cost: 100,
    requires_home_feature: 'has_deck',
  },

  // ═══ SEASONAL GENERAL ═══
  {
    id: 'spring-exterior-walkthrough',
    title: 'Spring Exterior Walkthrough',
    description: 'Walk the perimeter of your home checking for winter damage — cracks in foundation, caulk gaps, damaged siding.',
    instructions: [
      'Walk the entire perimeter of your home',
      'Check foundation for new cracks (mark them with tape to monitor)',
      'Inspect caulking around windows and doors — recaulk any gaps',
      'Look for damaged or loose siding, trim, or fascia',
      'Check grading — soil should slope away from the foundation',
      'Inspect the driveway and walkways for heaving or cracks',
      'Clear any debris from window wells',
    ],
    category: 'general',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [3, 4],
    estimated_minutes: 30,
    estimated_cost: 0,
  },
  {
    id: 'fall-winterize',
    title: 'Fall Winterization Checklist',
    description: 'Prepare your entire home for winter — the most important seasonal maintenance event of the year.',
    instructions: [
      'Winterize hose bibs and sprinkler system',
      'Reverse ceiling fan direction (clockwise in winter)',
      'Check weatherstripping on all exterior doors',
      'Inspect and clean the chimney before first use',
      'Test the furnace — turn on heat mode and verify operation',
      'Check insulation in the attic — add more if you can see the joists',
      'Caulk any gaps around windows and exterior penetrations',
      'Check that your emergency kit is stocked (flashlights, batteries, water)',
    ],
    category: 'seasonal',
    priority: 'high',
    frequency: 'annual',
    applicable_months: [10],
    estimated_minutes: 120,
    estimated_cost: 30,
  },

  // ═══ KITCHEN (from Proventive) ═══
  {
    id: 'refrigerator-coils-clean',
    title: 'Vacuum Refrigerator Coils & Compressor',
    description: 'Dust and pet hair buildup on refrigerator coils forces the compressor to work harder, reducing efficiency and lifespan. Clean every 6-12 months.',
    instructions: [
      'Unplug the refrigerator or turn off the breaker',
      'Locate the coils — usually behind or underneath the fridge',
      'Use a coil brush or vacuum with a brush attachment to remove dust and debris',
      'Clean the condenser fan blade if accessible',
      'Wipe down the area behind/under the fridge',
      'Plug the refrigerator back in',
      'Check the door seals while you are at it — a dollar bill should hold when closed in the seal',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'biannual',
    applicable_months: [3, 9],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'garbage-disposal-clean',
    title: 'Clean & Sharpen Garbage Disposal',
    description: 'Grease and food buildup causes odors and dulls the blades. Regular cleaning keeps it fresh and cuts efficiently.',
    instructions: [
      'Turn off the disposal and NEVER put your hand inside',
      'Drop a handful of ice cubes and a cup of rock salt into the disposal',
      'Run the disposal with cold water for 30 seconds — ice sharpens the blades',
      'Cut a lemon or lime in half and grind it to deodorize',
      'Pour 1/2 cup baking soda followed by 1 cup vinegar — let foam for 10 minutes',
      'Flush with hot water for 30 seconds',
      'Clean the rubber splash guard with a scrub brush and dish soap',
    ],
    category: 'appliance',
    priority: 'low',
    frequency: 'quarterly',
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 10,
    estimated_cost: 0,
  },
  {
    id: 'vent-hood-degrease',
    title: 'Degrease & Clean Range Vent Hood',
    description: 'Grease buildup on your range hood filter restricts airflow, causes odors, and is a fire hazard. Clean the filter and housing quarterly.',
    instructions: [
      'Remove the vent hood filter(s)',
      'Soak in hot water with dish soap and baking soda for 15-20 minutes',
      'Scrub with a non-abrasive brush to remove grease',
      'Wipe down the hood interior and exterior with a degreasing cleaner',
      'Rinse and dry the filter completely before reinstalling',
      'If you have a charcoal filter (recirculating hood), replace it every 3-6 months',
      'Check that the fan operates on all speeds',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'quarterly',
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'dishwasher-clean',
    title: 'Clean Dishwasher Interior & Filter',
    description: 'Food particles and mineral deposits build up in the filter and spray arms, reducing cleaning power and causing odors.',
    instructions: [
      'Remove the bottom rack and locate the filter (usually at the base)',
      'Twist and pull out the cylindrical filter',
      'Rinse under hot water and scrub with a soft brush to remove debris',
      'Check the spray arms for clogged holes — use a toothpick to clear them',
      'Wipe down the door edges, gasket, and interior walls',
      'Place a cup of white vinegar on the top rack and run a hot cycle empty',
      'Sprinkle 1 cup of baking soda on the bottom and run a short hot cycle',
      'Reinstall the clean filter',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'quarterly',
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },
  {
    id: 'stone-countertop-seal',
    title: 'Clean & Seal Stone Countertops',
    description: 'Granite and marble countertops need periodic resealing to prevent stains and etching. Test annually — reseal if water no longer beads on the surface.',
    instructions: [
      'Clean the countertop thoroughly with a pH-neutral stone cleaner',
      'Do the water bead test: sprinkle water on the surface — if it soaks in within 5 minutes, it needs resealing',
      'If resealing: make sure the surface is completely clean and dry',
      'Apply stone sealer with a clean cloth in small sections',
      'Let it absorb for 15-20 minutes (follow product instructions)',
      'Wipe off any excess sealer with a clean dry cloth',
      'Allow 24 hours to cure before heavy use',
    ],
    category: 'general',
    priority: 'low',
    frequency: 'annual',
    applicable_months: [4],
    estimated_minutes: 30,
    estimated_cost: 20,
  },

  // ═══ BATHROOM & LAUNDRY (from Proventive) ═══
  {
    id: 'washing-machine-clean',
    title: 'Clean Washing Machine',
    description: 'Mold, mildew, and detergent residue build up inside your washer, causing odors and reducing cleaning performance. Deep clean monthly or quarterly.',
    instructions: [
      'Run an empty hot cycle with 2 cups of white vinegar',
      'Wipe down the rubber door gasket with a vinegar-soaked cloth (front-loaders)',
      'Pull out and scrub the detergent/softener dispenser tray',
      'Clean the lint/debris filter (usually at the bottom front of front-loaders)',
      'Wipe the exterior and control panel',
      'Leave the door open after each use to prevent mildew',
      'For top-loaders: clean around the agitator and the rim',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'quarterly',
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },
  {
    id: 'drain-clearing',
    title: 'Clear & Maintain Household Drains',
    description: 'Hair, soap scum, and grease accumulate in drains over time. Proactive cleaning prevents slow drains and costly clogs.',
    instructions: [
      'Remove drain covers and pull out any visible hair or debris',
      'Pour 1/2 cup baking soda followed by 1/2 cup vinegar into each drain',
      'Let it fizz for 15-30 minutes, then flush with boiling water',
      'Use a drain snake or zip tool on slow drains to pull out deeper clogs',
      'Clean pop-up stoppers in bathroom sinks (lift and wipe off buildup)',
      'For kitchen sinks: run hot water for 30 seconds after each use',
      'Install mesh drain covers to catch hair and food particles',
    ],
    category: 'plumbing',
    priority: 'medium',
    frequency: 'quarterly',
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'bathroom-exhaust-fan-clean',
    title: 'Clean Bathroom Exhaust Fans',
    description: 'Dust-clogged exhaust fans cannot properly remove moisture, leading to mold growth, peeling paint, and poor air quality.',
    instructions: [
      'Turn off the fan at the switch or breaker',
      'Remove the fan cover (usually pulls down and unclips)',
      'Soak the cover in warm soapy water and scrub gently',
      'Use a vacuum with a brush attachment to clean dust from the fan blades and housing',
      'Wipe the motor housing with a damp cloth (do not get the motor wet)',
      'Dry and reinstall the cover',
      'Test that the fan runs smoothly and moves air properly',
      'Hold a tissue near the fan — it should be pulled toward it when running',
    ],
    category: 'appliance',
    priority: 'medium',
    frequency: 'biannual',
    applicable_months: [4, 10],
    estimated_minutes: 15,
    estimated_cost: 0,
  },

  // ═══ THROUGHOUT THE HOME (from Proventive) ═══
  {
    id: 'ceiling-fan-clean-reverse',
    title: 'Clean & Reverse Ceiling Fans',
    description: 'Dusty fan blades spread allergens. Reversing direction seasonally improves comfort — counterclockwise in summer (downdraft), clockwise in winter (updraft to circulate warm air).',
    instructions: [
      'Turn off the fan and let it stop completely',
      'Use a pillowcase over each blade to trap dust while wiping (prevents falling onto furniture)',
      'Wipe the motor housing and light fixtures',
      'Locate the direction switch on the fan body',
      'Set to COUNTERCLOCKWISE for summer (you should feel a breeze below)',
      'Set to CLOCKWISE for winter (pushes warm air from ceiling down the walls)',
      'Tighten any loose blade screws while you are up there',
    ],
    category: 'general',
    priority: 'low',
    frequency: 'biannual',
    applicable_months: [4, 10],
    estimated_minutes: 20,
    estimated_cost: 0,
  },
  {
    id: 'lightbulb-check',
    title: 'Check & Replace Burned-Out Lightbulbs',
    description: 'Walk through your home and replace any burned-out or flickering bulbs. Upgrade to LED where possible — they last 25x longer and use 75% less energy.',
    instructions: [
      'Walk through every room and check each light fixture',
      'Note any burned-out, flickering, or dim bulbs',
      'Check exterior lights including porch, garage, and landscape lighting',
      'Replace with LED bulbs where possible (match wattage and base type)',
      'Verify correct color temperature: warm white (2700K) for living spaces, daylight (5000K) for task areas',
      'Check that dimmer switches are compatible with LED bulbs (not all are)',
      'Dispose of old CFLs at a recycling center (they contain mercury)',
    ],
    category: 'electrical',
    priority: 'low',
    frequency: 'quarterly',
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 15,
    estimated_cost: 10,
  },

  // ═══ HOME UTILITIES (from Proventive) ═══
  {
    id: 'winterize-ac-condenser',
    title: 'Winterize A/C Condenser Unit',
    description: 'Protect your outdoor AC unit from winter debris and ice damage. Covering and clearing around the unit extends its life.',
    instructions: [
      'Turn off power to the AC unit at the exterior disconnect or breaker',
      'Remove any leaves, sticks, and debris from around and on top of the unit',
      'Rinse the condenser fins gently with a hose to remove remaining dirt',
      'Allow the unit to dry completely',
      'Place a breathable condenser cover over the top (do NOT wrap entirely — trapped moisture causes corrosion)',
      'Or place a piece of plywood on top weighted with a brick to keep debris out',
      'Clear a 2-foot perimeter around the unit from shrubs and mulch',
      'Check periodically in winter and remove any ice dams or heavy snow',
    ],
    category: 'hvac',
    priority: 'medium',
    frequency: 'annual',
    applicable_months: [11],
    estimated_minutes: 15,
    estimated_cost: 0,
    requires_equipment: 'hvac',
  },
  {
    id: 'air-exchanger-clean',
    title: 'Clean & Maintain Air Exchanger (HRV/ERV)',
    description: 'Heat Recovery Ventilators and Energy Recovery Ventilators need regular filter cleaning to maintain indoor air quality and efficiency.',
    instructions: [
      'Turn off the unit before servicing',
      'Remove and inspect the filters — vacuum or wash with mild soap and water',
      'Clean the heat exchange core — remove, rinse with warm water, and let dry',
      'Vacuum dust from inside the unit cabinet',
      'Check condensate drain for clogs — flush with warm water',
      'Inspect outdoor intake and exhaust hoods for blockages (bird nests, snow, leaves)',
      'Reinstall filters and core once dry',
      'Turn the unit back on and verify airflow from the vents',
    ],
    category: 'hvac',
    priority: 'medium',
    frequency: 'quarterly',
    applicable_months: [1, 4, 7, 10],
    estimated_minutes: 25,
    estimated_cost: 0,
  },
  {
    id: 'water-softener-salt',
    title: 'Refill Water Softener Salt',
    description: 'Check salt level monthly and refill as needed. Low salt means hard water passes through, causing scale buildup on pipes, fixtures, and appliances.',
    instructions: [
      'Open the brine tank lid and check the salt level',
      'Salt should be at least 3-4 inches above the water line',
      'If low, add salt pellets (evaporated salt pellets are recommended over rock salt)',
      'Break up any salt bridges (hardened crust) with a broom handle',
      'Check for a salt mush buildup at the bottom — scoop out if present',
      'Verify the system is regenerating on schedule (check the control panel)',
      'Clean the brine tank annually — drain, scrub, and refill with fresh salt',
    ],
    category: 'plumbing',
    priority: 'medium',
    frequency: 'monthly',
    applicable_months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    estimated_minutes: 10,
    estimated_cost: 15,
  },

  // ═══ OUTDOOR (from Proventive) ═══
  {
    id: 'garbage-bins-clean',
    title: 'Clean Garbage & Recycling Bins',
    description: 'Bacteria, odors, and pests thrive in dirty bins. A quarterly scrub keeps them sanitary and reduces attracting wildlife.',
    instructions: [
      'Roll bins to a driveway or concrete surface (not the lawn)',
      'Rinse the inside with a garden hose',
      'Spray with a mixture of dish soap, baking soda, and white vinegar',
      'Scrub the interior with a long-handled brush',
      'Rinse thoroughly and let air dry in the sun (UV kills bacteria)',
      'Sprinkle baking soda in the bottom to absorb future odors',
      'In hot months, consider double-bagging food waste to reduce maggot risk',
    ],
    category: 'outdoor',
    priority: 'low',
    frequency: 'quarterly',
    applicable_months: [3, 6, 9, 12],
    estimated_minutes: 15,
    estimated_cost: 0,
  },
];

// ─── Get tasks applicable for a given month ───
export const getTasksForMonth = (
  month: number,
  homeFeatures: { has_pool: boolean; has_deck: boolean; has_sprinkler_system: boolean }
): TaskTemplate[] => {
  return TASK_TEMPLATES.filter((task) => {
    if (!task.applicable_months.includes(month)) return false;
    if (task.requires_home_feature === 'has_pool' && !homeFeatures.has_pool) return false;
    if (task.requires_home_feature === 'has_deck' && !homeFeatures.has_deck) return false;
    return true;
  });
};

// ─── Equipment categories with display info ───
export const EQUIPMENT_CATEGORIES = [
  { id: 'hvac', label: 'HVAC / Air Conditioning', icon: 'thermometer', color: '#2196F3' },
  { id: 'water_heater', label: 'Water Heater', icon: 'flame', color: '#FF9800' },
  { id: 'roof', label: 'Roof & Gutters', icon: 'home', color: '#795548' },
  { id: 'plumbing', label: 'Plumbing', icon: 'water', color: '#00BCD4' },
  { id: 'electrical', label: 'Electrical', icon: 'flash', color: '#FFC107' },
  { id: 'appliance', label: 'Appliances', icon: 'settings', color: '#607D8B' },
  { id: 'outdoor', label: 'Outdoor', icon: 'leaf', color: '#8BC34A' },
  { id: 'safety', label: 'Safety Systems', icon: 'shield-checkmark', color: '#E53935' },
  { id: 'pool', label: 'Pool & Hot Tub', icon: 'water', color: '#03A9F4' },
  { id: 'garage', label: 'Garage', icon: 'car', color: '#9E9E9E' },
] as const;
